INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(144, 123, 'Nature', 'https://images.pexels.com/photos/1005261/pexels-photo-1005261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', CURRENT_TIMESTAMP);
INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(223434, 123, 'Exercise', 'https://images.pexels.com/photos/258045/pexels-photo-258045.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=350', CURRENT_TIMESTAMP);
INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(3435435, 123, 'Space', 'https://images.pexels.com/photos/1169754/pexels-photo-1169754.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', CURRENT_TIMESTAMP);
INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(44553, 123, 'Diet', 'https://images.pexels.com/photos/5876/food-salad-healthy-vegetables.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350', CURRENT_TIMESTAMP);
INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(56666, 123, 'Relax', 'https://images.pexels.com/photos/92870/pexels-photo-92870.jpeg?auto=compress&cs=tinysrgb&h=350', CURRENT_TIMESTAMP);
INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(6444, 123, 'Relationships', 'https://images.pexels.com/photos/1269025/pexels-photo-1269025.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=350', CURRENT_TIMESTAMP);
INSERT INTO topic(id, user_id, name, background_image_url, create_timestamp) VALUES(777, 123, 'Knowledge', 'https://images.pexels.com/photos/34592/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350', CURRENT_TIMESTAMP);

INSERT INTO message(id, topic_id, user_id, message, create_timestamp) VALUES(324324, 144, 123, 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \''Content here, content here\', CURRENT_TIMESTAMP);
INSERT INTO message(id, topic_id, user_id, message, create_timestamp) VALUES(324325, 144, 123, 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.', CURRENT_TIMESTAMP);
INSERT INTO message(id, topic_id, user_id, message, create_timestamp) VALUES(324326, 144, 123, 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \''Content here, content here\', CURRENT_TIMESTAMP);
INSERT INTO message(id, topic_id, user_id, message, create_timestamp) VALUES(324327, 144, 123, 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \''Content here, content here\', CURRENT_TIMESTAMP);
INSERT INTO message(id, topic_id, user_id, message, create_timestamp) VALUES(324328, 10, 123, 'Chicken comes befores the egg', CURRENT_TIMESTAMP);

INSERT INTO book(id, title, alt, author, src, create_timestamp) VALUES (13424, 'altruism', 'altruism', 'mattieu ricard', 'images/altruism.png', CURRENT_TIMESTAMP);
INSERT INTO book(id, title, alt, author, src, create_timestamp) VALUES (22424, 'grit', 'grit', 'angela duckworth', 'images/grit.png', CURRENT_TIMESTAMP);
INSERT INTO book(id, title, alt, author, src, create_timestamp) VALUES (32343, 'the alchemist', 'the alchemist', 'paulo coelho', 'images/alchemist.png', CURRENT_TIMESTAMP);
INSERT INTO book(id, title, alt, author, src, create_timestamp) VALUES (42343, 'little prince', 'little prince', 'antoine de saint exupery', 'images/littleprince.png', CURRENT_TIMESTAMP);
INSERT INTO book(id, title, alt, author, src, create_timestamp) VALUES (54444, 'meditations', 'meditations', 'marcus aurelius', 'images/meditations.png', CURRENT_TIMESTAMP);
